"""migration

Revision ID: ec76d53d758a
Revises: 8069cfef57e7
Create Date: 2026-05-06 17:15:54.236676
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ec76d53d758a'
down_revision: Union[str, None] = '8069cfef57e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
