"""them bang call_logs

Revision ID: 2071f9e51b07
Revises: ba1e869939f8
Create Date: 2026-04-24 15:38:42.840837
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2071f9e51b07'
down_revision: Union[str, None] = 'ba1e869939f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
