"""them cot ward vao stores

Revision ID: 0ee4d74592bf
Revises: fbd4effaa742
Create Date: 2026-04-23 15:38:09.152525
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0ee4d74592bf'
down_revision: Union[str, None] = 'fbd4effaa742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
