"""migration

Revision ID: c14464844578
Revises: 2071f9e51b07
Create Date: 2026-04-27 10:34:37.696707
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c14464844578'
down_revision: Union[str, None] = '2071f9e51b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkin_sessions', sa.Column('photo_public_id', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkin_sessions', 'photo_public_id')
    # ### end Alembic commands ###
