"""migration

Revision ID: 4437c6183186
Revises: 23339f78326a
Create Date: 2026-04-23 12:11:01.504962
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4437c6183186'
down_revision: Union[str, None] = '23339f78326a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
