"""migration

Revision ID: 25552f7d0844
Revises: 317caf3eb392
Create Date: 2026-05-20 10:22:16.615792
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '25552f7d0844'
down_revision: Union[str, None] = '317caf3eb392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('old_lat', sa.Float(), nullable=True),
    sa.Column('old_lon', sa.Float(), nullable=True),
    sa.Column('new_lat', sa.Float(), nullable=False),
    sa.Column('new_lon', sa.Float(), nullable=False),
    sa.Column('delta_m', sa.Float(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_logs')
    # ### end Alembic commands ###
