"""migration

Revision ID: a324d4ecf325
Revises: 7de4b9bac5b9
Create Date: 2026-04-24 13:10:26.024678
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a324d4ecf325'
down_revision: Union[str, None] = '7de4b9bac5b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('photo2_url', sa.Text(), nullable=True))
    op.add_column('checkins', sa.Column('photo3_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkins', 'photo3_url')
    op.drop_column('checkins', 'photo2_url')
    # ### end Alembic commands ###
