"""them cot ward vao stores

Revision ID: fbd4effaa742
Revises: 4437c6183186
Create Date: 2026-04-23 15:33:53.118573
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fbd4effaa742'
down_revision: Union[str, None] = '4437c6183186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('ward', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'ward')
    # ### end Alembic commands ###
