"""them cot ward vao stores

Revision ID: c08aaa3d2916
Revises: 0ee4d74592bf
Create Date: 2026-04-23 15:44:10.000196
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c08aaa3d2916'
down_revision: Union[str, None] = '0ee4d74592bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
