"""them bang session va settings

Revision ID: 7de4b9bac5b9
Revises: c08aaa3d2916
Create Date: 2026-04-24 12:18:24.782918
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7de4b9bac5b9'
down_revision: Union[str, None] = 'c08aaa3d2916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkin_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('checkin_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checkin_lat', sa.String(length=32), nullable=True),
    sa.Column('checkin_lon', sa.String(length=32), nullable=True),
    sa.Column('photo1_url', sa.String(length=512), nullable=True),
    sa.Column('photo1_lat', sa.String(length=32), nullable=True),
    sa.Column('photo1_lon', sa.String(length=32), nullable=True),
    sa.Column('photo1_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('photo2_url', sa.String(length=512), nullable=True),
    sa.Column('photo2_lat', sa.String(length=32), nullable=True),
    sa.Column('photo2_lon', sa.String(length=32), nullable=True),
    sa.Column('photo2_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('photo3_url', sa.String(length=512), nullable=True),
    sa.Column('photo3_lat', sa.String(length=32), nullable=True),
    sa.Column('photo3_lon', sa.String(length=32), nullable=True),
    sa.Column('photo3_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    op.drop_table('checkin_sessions')
    # ### end Alembic commands ###
