"""migration

Revision ID: 317caf3eb392
Revises: ec76d53d758a
Create Date: 2026-05-06 17:22:32.785467
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '317caf3eb392'
down_revision: Union[str, None] = 'ec76d53d758a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
