"""migration

Revision ID: 8069cfef57e7
Revises: 2468df1e84a6
Create Date: 2026-05-06 17:12:46.306475
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8069cfef57e7'
down_revision: Union[str, None] = '2468df1e84a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
