"""initial schema

Revision ID: 23339f78326a
Revises: 
Create Date: 2026-04-23 11:05:12.068043
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '23339f78326a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assignments_user_id_fkey', 'assignments', type_='foreignkey')
    op.drop_constraint('assignments_store_id_fkey', 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'assignments', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key('assignments_store_id_fkey', 'assignments', 'stores', ['store_id'], ['id'])
    op.create_foreign_key('assignments_user_id_fkey', 'assignments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
