"""migration

Revision ID: 2468df1e84a6
Revises: c14464844578
Create Date: 2026-05-06 14:43:33.126826
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2468df1e84a6'
down_revision: Union[str, None] = 'c14464844578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
